[versions]
agp = "8.3.2"
datastoreCore = "1.1.0"
kotlin = "1.9.23"
kotlin-coroutines = "1.7.3"
coreKtx = "1.12.0"
kotlinxSerializationJson = "1.6.2"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
#compose
composeBom = "2024.04.00"
compose-navigation = "2.7.7"
compose-constraint-layout = "1.0.1"
#other
protobufJavalite = "3.18.0"
protobufKotlinLite = "3.21.11"
retrofit = "2.11.0"
okhttp = "4.12.0"

arrow = "1.2.1"
coil-compose = "2.4.0"
kotlin-converter = "1.0.0"
protobuf = "0.9.4"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastoreCore" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
#compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
compose-constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "compose-constraint-layout" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-compose" }
icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
#kotlin coroutines
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
#retrofit
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
protobuf-kotlin-lite = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobufKotlinLite" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
kotlin-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "kotlin-converter" }
#okhttp
okhttp-client = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobufPlugin = { id = "com.google.protobuf", version.ref = "protobuf" }

